services:
  postgres-song-service:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=song-service-db
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - 5432

  app:
    build:
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-song-service/song-service-db
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    image: 'song-service'
    ports:
      - 8081:8081
    depends_on:
      - postgres-song-service